version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: some-pwd
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432