"""init-db

Revision ID: 12a3530f7109
Revises:
Create Date: 2020-11-19 14:37:37.367489

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from abilling.app.config import config

revision = '12a3530f7109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'client',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'date',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=config.DB_PG_SCHEMA,
    )
    op.create_table(
        'wallet',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('client_id', sa.BigInteger(), nullable=False),
        sa.Column(
            'balance',
            sa.DECIMAL(),
            server_default=sa.text('0'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['client_id'],
            [f'{config.DB_PG_SCHEMA}.client.id'],
            name='fk_wallet_client_id',
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=config.DB_PG_SCHEMA,
    )
    op.create_index(
        'ix_wallet_client_id',
        'wallet',
        ['client_id'],
        unique=False,
        schema=config.DB_PG_SCHEMA,
    )
    op.create_table(
        'operation_history',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            'date',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('wallet_id', sa.BigInteger(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'ACCRUAL',
                'WRITE_OFF',
                name='operation_type',
                schema=config.DB_PG_SCHEMA,
            ),
            nullable=False,
        ),
        sa.Column('amount', sa.DECIMAL(), nullable=False),
        sa.Column('description', sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ['wallet_id'],
            [f'{config.DB_PG_SCHEMA}.wallet.id'],
            name='fk_operation_history_wallet_id',
        ),
        sa.PrimaryKeyConstraint('id'),
        schema=config.DB_PG_SCHEMA,
    )
    op.create_index(
        'ix_operation_history_wallet_id',
        'operation_history',
        ['wallet_id'],
        unique=False,
        schema=config.DB_PG_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_operation_history_wallet_id',
        table_name='operation_history',
        schema=config.DB_PG_SCHEMA,
    )
    op.drop_table('operation_history', schema=config.DB_PG_SCHEMA)
    op.drop_index(
        'ix_wallet_client_id',
        table_name='wallet',
        schema=config.DB_PG_SCHEMA,
    )
    op.drop_table('wallet', schema=config.DB_PG_SCHEMA)
    op.drop_table('client', schema=config.DB_PG_SCHEMA)
    sa.Enum(
        name='operation_type',
        schema=config.DB_PG_SCHEMA,
    ).drop(op.get_bind())
    # ### end Alembic commands ###
