name: tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --entrypoint "python -m pytest -vvs" abilling-test